# Practice of linear algebra concepts for AI/ML

In [1]:
import numpy as np

# Vector 1

In [21]:
lst1 = [1,2,3]
lst2 = [4,5,6]

vec1 = np.array(lst1)
print("Horizontal Vector")
print(vec1)
vec2 = np.array(lst2)
print("Horizontal Vector")
print(vec2)

Horizontal Vector
[1 2 3]
Horizontal Vector
[4 5 6]


# Basic Vector Operations

In [22]:
addition = vec1 + vec2
print("The vector addition: "       + str(addition))

subtraction = vec1 - vec2
print("subtraction of vector: "     + str(subtraction))

multiplication = vec1 * vec2
print("Multiplication of Vector:   " + str(multiplication))

division = vec1 / vec2
print("Division of Vector:        " + str(division))

scalar = 2
scalar_mul = vec1 * scalar
print("The scalar multiplication is: "    + str(scalar_mul))

The vector addition: [5 7 9]
subtraction of vector: [-3 -3 -3]
Multiplication of Vector:   [ 4 10 18]
Division of Vector:        [0.25 0.4  0.5 ]
The scalar multiplication is: [2 4 6]


In [23]:
#Dot Product

dot_pro = vec1.dot(vec2)
print("the dot_product       :" + str(dot_pro))

#cross Product
cross = np.cross(vec1, vec2)
print(cross)


the dot_product       :32
[-3  6 -3]


In [24]:
# l1 norm 
from numpy.linalg import norm 
arr = np.array([1,3,7])
l1 = norm(arr, 1)
print(l1)


11.0


In [25]:
# l2 norm 
arr = np.array([1,2,4])
l2 = norm(arr, 2)
print(l2)

4.58257569495584


In [27]:
# infinity norm

from numpy import array, inf
from numpy.linalg import norm 

v = array([1,3,6,7])
vecmax = norm(v, inf)
print(vecmax)

7.0


# Vector Projection

In [28]:
v = np.array([1,2,3])
u = np.array([4,7,8])

# find the norms of the vector v
v_norm = np.sqrt(sum(v**2))

# find the dot product using dot product()

projec_of_u_on_v = (np.dot(u,v)/v_norm**2)*v
print("projection of u on v vector      :" , projec_of_u_on_v)



projection of u on v vector      : [3. 6. 9.]


# linear Combination of vector

In [29]:
x = np.array([[0,0,1],
             [0,1,0],
             [1,0,0]])
y = ([3.67, 6.5, 7.8])

scalars = np.linalg.solve(x, y)
scalars




array([7.8 , 6.5 , 3.67])

# Linear dependent and Independent vectors

In [31]:
import sympy

matrix = np.array([[0,5,1],
                 [0,10,0]
                  ])
_, indexes = sympy.Matrix(matrix).T.rref() # T for transpose
print(indexes)

(0, 1)


# Check Indexes

In [34]:
# find the indexes
print(matrix[indexes, :])

[[ 0  5  1]
 [ 0 10  0]]


In [36]:
# check vector is linear dependent or not 

if len(indexes) == 2:
    print("Linear independent")

else:
    print("Linear dependent")


Linear independent
